services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: pgvector_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  oso:
    build:
      context: .
      dockerfile: oso.Dockerfile
    container_name: oso
    restart: always
    ports:
      - "8081:8081"

volumes:
  pgvector_data:
