services:
  db:
    image: postgres:17.4
    env_file:
      - ../.env

  api:
    build:
      context: ..
      dockerfile: ./prod/Dockerfile
    image: fastapirag
    ports:
      - "80:80"
    env_file:
      - ../.env
    depends_on:
      - db
    restart: always
