services:
  db:
    image: ankane/pgvector:v0.5.1
    restart: always
    env_file:
      - ../.env
    volumes:
      - pgvector_data:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: ./prod/Dockerfile
    image: fastapirag
    ports:
      - "80:80"
    env_file:
      - ../.env
    depends_on:
      - db
    restart: always

volumes:
  pgvector_data:
