name: Run Tests with pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ARCHIVE_URL: "https://oso-local-development-binary.s3.amazonaws.com/latest/oso-local-development-binary-linux-x86_64.tar.gz"
      OUTPUT_FILENAME: "oso-dev-server.tar.gz"
      OSO_URL: "http://localhost:8080"
      DEV_OSO_URL: "http://localhost:8080"
      OSO_API_KEY: "e_0123456789_12345_osotesttoken01xiIn"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Wait for PostgreSQL
        run: sleep 10

      - name: Prepare Database
        run: |
          PGPASSWORD=test_password psql -h localhost -U test_user -d test_database -c "CREATE EXTENSION IF NOT EXISTS vector;"

      - name: Install Oso Cloud CLI
        run: |
          curl -L https://cloud.osohq.com/install.sh | bash

      - name: Install Oso Dev Server
        run: |
          curl ${ARCHIVE_URL} --output ${OUTPUT_FILENAME}
          tar -xzf ${OUTPUT_FILENAME}
          rm ${OUTPUT_FILENAME}
          chmod 0700 standalone

      - name: Start Oso Dev Server in the background
        run: |
          ./standalone oso/policy.polar &

      - name: Run Tests with pytest
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_database
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_database
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          OPENAI_API_KEY: fake
        run: pytest
